version: '2'

services:

  stomp:
    container_name: stomp
    image: flybetter/stomp:p6
    depends_on:
    - activemq
    environment:
    - PY_OFFICAL_MYSQL
    - PY_TARGET_MYSQL
    network_mode: "host"
    restart: always

  blockCompare:
    container_name: block_handler
    image: flybetter/block_handler:p3
    environment:
    - PY_OFFICAL_MYSQL
    - PY_TARGET_MYSQL
    depends_on:
    - activemq
    network_mode: "host"
    restart: always

  activemq:
    container_name: activemq
    image: rmohr/activemq
    depends_on:
    - house-repo
    - beike
    ports:
    - "8161:8161"
    - "61616:61616"
    - "61613:61613"
    network_mode: "host"

  house-repo:
    container_name: house-repo
    image: flybetter/house-repo:p1
    environment:
    - JAVA_MYSQL
    - USER
    - PASSWORD
    network_mode: "host"

  stompFilter:
    container_name: stomp_filter
    image: flybetter/stomp_filter:v1
    environment:
    - PY_OFFICAL_MYSQL
    - PY_TARGET_MYSQL
    network_mode: "host"


  beike:
    container_name: beike
    image: flybetter/beike:v4
    network_mode: "host"

