ersion: '2'

services:

  stomp:
    container_name: stomp
    image: flybetter/stomp:p3
    depends_on:
    - activemq
    environment:
    - PY_OFFICAL_MYSQL
    - PY_TARGET_MYSQL
    network_mode: "host"
    restart: always

  blockCompare:
    container_name: block_handler
    image: flybetter/block_handler:p3
    environment:
    - PY_OFFICAL_MYSQL
    - PY_TARGET_MYSQL
    depends_on:
    - activemq
    network_mode: "host"
    restart: always

  activemq:
    container_name: activemq
    image: rmohr/activemq
    depends_on:
    - house-repo
    - 5i5j
    - beike
    - century21
    - lianjia
    ports:
    - "8161:8161"
    - "61616:61616"
    - "61613:61613"
    network_mode: "host"

  house-repo:
    container_name: house-repo
    image: flybetter/house-repo:p1
    environment:
    - JAVA_MYSQL
    - USER
    - PASSWORD
    network_mode: "host"

  5i5j:
    container_name: 5i5j
    image: flybetter/5i5j:v3
    network_mode: "host"

  beike:
    container_name: beike
    image: flybetter/beike:v2
    network_mode: "host"

  century21:
    container_name: century21
    image: flybetter/century21:v3
    network_mode: "host"

  lianjia:
    container_name: lianjia
    image: flybetter/lianjia:v3
    network_mode: "host"